### ISSUE TITLE
Named template management tool

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#108]
I'd had this down as a future feature but logging it now because it might be more relevant now with regards to doing more persistent hosts files functionality as its quite a similar problem.

Currently metalware uses a host file distributed around the deployed nodes at build time in order to provide basic DNS resolution around a platform. Thats OK for basic clusters but in general, we switched to doing proper DNS on our managed clusters a few years ago because its considerably more flexible and resilient, its generally slower but we havn't really seen any problems in the last few years..

So as I see it, the basic use case would be...

Some templates in metalware-default for each network (forward and reverse)..
eg..
forwards...
```
$TTL 300
@                       IN      SOA     <%=hostip%>. nobody.example.com. (
                                        <%= getrubytomakeatimestring %>   ; Serial
                                        600         ; Refresh
                                        1800         ; Retry
                                        604800       ; Expire
                                        300          ; TTL
                                        )

                        IN      NS      $cobbler_server.
@       IN MX   <%=hostip.quad4 %>  <%=hostip%>.<%=domain%>

IN NS <%=hostip%>.

<% for each machine with a private network IP %>
<%=hostname%> IN A <%=ip%>;
<% end %> 
```
reverse...
```
$TTL 300
@                       IN      SOA     <%=hostip%>. nobody.example.com. (
                                        <%= getrubytomakeatimestring %>   ; Serial
                                        600         ; Refresh
                                        1800         ; Retry
                                        604800       ; Expire
                                        300          ; TTL
                                        )

                        IN      NS      <%=hostip%>.
<% for each machine with a private network IP %>
<%=ip.quad4%>.<%ip.quad3%>    IN PTR  <%=hostsFQDNonthisnetwork%>.;
<% end %>
```

Each time a new host / group of hosts are added, these templates (for all networks) would need to be regenerated and named restarted to pick up the changes..

Theres more I could add (the setup of named etc) but thats pretty much what we'd actually need to get metalware to do dynamically. Hopefully gives you guys an initial idea of the use case so we can discuss. 

Mazin - let me know your thoughts..

**Comment by bobwhitelock** [comment]
@ste78: Hi Steve - I've got a few questions on this:

- For the forward/reverse network templates, I'm assuming these only live on the Metalware deployment server, and don't need to be made available to nodes?

- For 

  > Each time a new host / group of hosts are added, these templates (for all networks) would need to be regenerated and named restarted to pick up the changes..

   -> does this mean when a `configure node` / `configure group` command is run, or when a node is picked up by `hunter`? Or something else?

- Should this new functionality live in alongside the ability to automatically generate the `hosts` file, and a user can select which to use (I've added automatically regenerating the `hosts` file recently, so you've probably not used it yet)? Or should this replace that entirely?

My initial thoughts are this doesn't look like it should be too tricky to add, it looks like this will mostly involve wiring together a few bits of Metalware functionality which already exist. But we can discuss more on Wednesday.

**Comment by ste78** [comment]
- yep, rendered templates would be installed to /var/lib/named/ on the same machine as metalware. 

- templates re-rendered each time configure is run (as with hosts) or now manually with a sync tool as we've discussed. 

- named functionality would be a more advanced option than using hosts files, so I'd think there would need to be a high level metalware configure option (use hosts or named)

**Comment by ColonelPanicks** [comment]
Some notes on getting a working named setup and things to consider/fix for metalware integration.

**Installation**

* One-time configuration handled in the `metalware.sh` script ([script here](https://github.com/alces-software/knowledgebase/blob/master/epel/7/metalware/metalware.sh#L107))
* Zone configuration files generated with `named.sh` script ([script here](https://github.com/alces-software/knowledgebase/blob/master/epel/7/named/named.sh))

**Issues/Notes**

* For the network zones, there should be a zone for every defined network. Currently this is done by looping through `networks.each` for the metalware master server however this won't include any networks defined in group/node files
* The `bmc` network sits underneath `mgt` which causes a couple of issues with the zone setup (e.g. `12.10` zone will need to include both `mgt` and `bmc` addresses for systems)
* Ideally there'll be some sort of `configure` command to run before `domain` config that will handle the TFTP, Named and DHCP setup from `metalware.sh` with user responses

**Comment by WilliamMcCumstie** [comment]
From discussions with @ColonelPanicks,

The major change that will be required is re-rendering the `named` templates instead of the `hosts` templates. This can be achievable by altering what is rendered in `DomainTemplatesRenderer` which should then be picked up when the `configure` commands are ran.

However their are two stages two `named`: 1) setup of the `named` server and 2) adding the networks two it. The adding off the networks should be reasonable straight forward (as mentioned above). However the setup of the `named` is the slightly trickier bit. We essentially need to decide whether we are going to perform a `hosts` file build or a `named` build.

My purposed solution is the addition of a `metal configure setup` command. Here it will ask predefined questions internal to metalware about which type of build you want to perform. It will not be dependant on the repo as it will determine what is required from the repo. Then it will then save it's responses NOT in `answers/setup.yaml` but instead in `config.yaml`.

Then we can possible have metalware automatically asking required questions as part of `metal configure domain/group/node`, possible in a different section.

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: I'm not convinced we need a new command for this. We already ask questions related to the Metalware server itself when you `configure domain`, and we now have the rendered `server.yaml` which contains server-related properties which we need to know about up-front.

I suggest you add a property to `server.yaml`, or maybe just in the repo config directly, named something like `hosts_method`. This can either be a required feature of a valid Metalware repo or we can just use a default value if it's not present, I'm not sure which is better. It can be defined as either `hosts` or `named` in the rendered file made available to Metalware, and in the repo can be defined in any, repo-dependent way - for instance in the default repo you could define it in terms of a question answer, and have a new domain question with a `choice` value with both of these options. This seems simpler and means one less command people need to run to set things up.

**Comment by ColonelPanicks** [comment]
In terms of `metalware-default`

**Comment by ColonelPanicks** [comment]
(oops, clicked the wrong button)

**Comment by ColonelPanicks** [comment]
In terms of `metalware-default` I'll be breaking down the `named.sh` from the knowledgebase into it's 3 configuration parts in the default repo. Will post back on here when that's sorted.

**Comment by WilliamMcCumstie** [comment]
@bobwhitelock, It is definitely possible to define it as part of `metal configure domain`. However, if we have particular questions that are part of the definition of a valid repo, would it not be better to define them in metalware itself?

Possible store the questions in a `required-questions.yaml` as part of metalware. Then when we load `configure.yaml` we merge the two hashes and make sure that the question has not been redefined as this could lead to weird bugs.

This may require defining a hierarchical structure to the questions, not sure at this point

**Comment by ColonelPanicks** [comment]
There are now the following files:

- `named/default` - This file generates the contents that should go into `/etc/named/metalware.conf`, it will create a zone for every network that is defined in `domain.yaml` (if named fails to start then may need to `chmod 644` the file)
- `named/forward/default` & `named/reverse/default` - Each zone (e.g. each defined network) is setup in its own config file, currently these scripts handle the loop through networks to create all of the zone files but if this should be moved outside of here then we'll need to think about making it part of the metalware stuff
- Additionally, `/etc/hosts` on the systems should only look like the following (although not too sure where this should be managed)
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

<%= alces.hostip %>  deploy.pri.<%= domain %> deploy.<%= domain %> deploy
```
- Much like with `/etc/hosts`, `/etc/resolv.conf` will need to look like the following for all slave systems
```
search <% networks.each do |zone, net| -%><% if net.defined -%><%= zone %>.<%=domain %> <% end %><% end %>
nameserver <%= alces.hostip %>
```

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: A couple of reasons I think we don't want to embed this too much in Metalware itself, at least at this point:

- We already have various requirements and options picked up by Metalware for a valid repo; one more shouldn't be an issue. If we find these are causing issues or we want to pull things in to the Metalware core we can always do so then; we can also add more validation of the different repo parts when you `repo use` it if needed.

- Although the option itself will be picked up by Metalware, the way this is specified may vary between repos - e.g. the default repo might have a domain question where you can choose between the 2 options, but we may also have a very locked down repo for particular customers which doesn't have this question, and just always renders `named` templates.

**Comment by ColonelPanicks** [comment]
A couple of little fixes needed to get named working:

- Replace `<%= external_dns %>` with `<%= externaldns %>` in `/opt/metalware/templates/named.conf.erb`

- Create an empty file at `/etc/named/metalware.conf` so that the file exists and named doesn't fail out

**Comment by ColonelPanicks** [comment]
Due to the change in name resolution `gethostip` no longer works. This is used both in `metalware-default/dhcp/default` and `metalware/src/node.rb`. The temp fix I used for the dhcp file was `<% alces.groups do |group| %><% group.nodes do |node| %><% if node.alces.nodename == hostname %><%= node.networks.pri.ip %><% end %><% end %><% end %>` but depending on how we fix the usage of it in metalware itself may change this solution too.

Thoughts?

**Comment by bobwhitelock** [comment]
@ColonelPanicks: I'm not sure, possibly @ste78 knows? Presumably there's some way we do the equivalent of `gethostip` for clusters using named normally?

**Comment by ColonelPanicks** [comment]
As it hasn't been mentioned in context of this issue - `gethostip` has been fixed by ensuring that the controller uses itself as a nameserver so there's no need to change the way that DHCP templates or any other components that use `gethostip` work. 

On another note, @WilliamMcCumstie, the named service needs to be reloaded at the end of a configure (`systemctl reload named`). If I were to add a new group (`metal configure group nodes`) then I can see the nodes properly added in `/var/named/*` however `gethostip node01` returns unknown host until named is reloaded.

**Comment by bobwhitelock** [comment]
@ColonelPanicks: didn't see this before merging the Named PR, @WilliamMcCumstie can you make that addition in a new PR?
