### ISSUE TITLE
Metal host self configuration

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#141]
From a clean CentOS image we want to be able to run the metalware installer, pull the default repo, run a 'metal configure domain' and the metalware host should be configured to be a deployment server with configuration specific to the domain.

A basic list of the information that would affect how the metal host was configured would be:
- PRV/MGT/EXT IP's and existence of those networks / masks gateways etc. 
- DOMAINNAMES for each network
- External service information (dns servers / proxies / ntp servers etc)

After that information is requested a host configure script would be run, example of how that would look is here: https://github.com/alces-software/knowledgebase/blob/master/epel/7/metalware/metalware.sh

That should be re-runable so every time 'metal configure domain' is run the host will reconfigure for any changes to network details etc. 

Having this allows us to then be able to ship part configured metalware appliances, on which the first thing that happens is a reconfiguration to suit the environment.

**Comment by ste78** [comment]
Some implementation thoughts to help get ideas started..

- I'm initially thinking that a metalmaster is setup as a node and a metalmaster.yaml file that holds any specfic parameters for it (eg IP), metalware could then render a set of 'files' for it in the usual way
- Being able to render non-kickstart based install file sets might help with the metalmaster configure process (ie a set of scripts end up in /var/lib/metware/rendered that are designed to be run directly rather than called through the kickstart process - the metal configure domain sequence would then call that script set for the metalmaster each time its run (or that could be a process you call manually `metal mastersync` for example)

**Comment by bobwhitelock** [comment]
@ste78: I'm not entirely sure how this fits into the existing Metalware features - unless I'm missing something, we already support the following:

> A basic list of the information that would affect how the metal host was configured would be:
> 
> PRV/MGT/EXT IP's and existence of those networks / masks gateways etc.
> DOMAINNAMES for each network
> External service information (dns servers / proxies / ntp servers etc)
 
by defining these properties in the config; they can also be set to the answers of configure questions to be asked when configuring.

For

> After that information is requested a host configure script would be run, example of how that would look is here: https://github.com/alces-software/knowledgebase/blob/master/epel/7/metalware/metalware.sh
> 
> That should be re-runable so every time 'metal configure domain' is run the host will reconfigure for any changes to network details etc.

is this the same/similar to https://trello.com/c/ZmBs7IB3/141-create-tftpboot-on-install, as discussed in the last meeting? Essentially we need some way to render one or more template scripts for the Metalware server itself; these templates will then be run in some way with every `metal configure domain`, or possibly every `metal configure`, command.

**Comment by ste78** [comment]
Yep we support setting those, they are examples of the configs required by the metal host re-configure scripts so just noting they'll need to be questions/answers in the default repo so as to provide a more complete use-case for the enhancement. 

Yep, its the same - but as a github issue with hopefully more detail. How do you want to track enhancements, do you prefer we put them in trello?
