### ISSUE TITLE
Metal build flags for generating files

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#145]
In some cases it would be run only parts of the build process. For example, only building the scripts for a node/group.

The idea here is to create flags for `metal build`, like:
- `--scripts` - Only generate scripts
- `--pxe` - Only generate the PXE boot file
- `--ks` - Only generate the kickstart file

**Comment by ste78** [comment]
I think this links with the second part of #141 whereby we need to sometimes just be able render a set of files rather than the full pxe-ks-scripts process. Rather than separate options for pxe ks etc, i was thinking something more like 'metal build --method [kickstart|basic]' might be cleaner

**Comment by bobwhitelock** [comment]
From meeting: will do this with a repo config value, which defines if node should be built in `kickstart` or `basic` way; `basic` method will just render the `files` and provide file equivalent to `kickstart`'s `post` section to run scripts for node. Up to user to then curl this.

**Comment by bobwhitelock** [comment]
This should be resolved when the above PR is merged; an example of using the method we chose to support this is already in the default repo in https://github.com/alces-software/metalware-default/commit/e389377c7a315d0c7062d849b19db3103c5d898a.
