### ISSUE TITLE
Hierarchal config file structure for ERb templating functionality

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#16]
Now metalware is relying more on ERb templating for many of its tools we should look into being able to populate variables from config files, rather than have to specify everything on the cli. Ultimately this should allow us replace much of the functionality given by the puppet hiera configuration in the symphony toolset and drop puppet from deployment completely. 

I see it working something like this:

- YAML config files in <metalwarehome>/etc/config/
- config files load into a primary config hash, but in order (so individual parameters can be overwritten by config files further in the chain (much like puppet hiera) 
- hard code config load order to
1) site.yaml
2) cluster.yaml
3) %gendersgroupname%.yaml where one is available
4) %nodename%.yaml where one is available

The resulting hash would then be used when rendering any ERb template within metalware.

**Comment by WilliamMcCumstie** [comment]
Clarifying options 3 and 4.
I assume option 3 is referring to [nodename].yaml and option 4 is a duplicate?

**Comment by ste78** [comment]
I'd accidentally invented some markup, I've edited above also:

3. %gendersgroupname%.yaml where one is available
4. %nodename%.yaml where one is available

**Comment by WilliamMcCumstie** [comment]
On closer inspection most of this information is specified in the genders folder. Would it be better to match the config file naming accordingly? Then we can load the config files in the reverse order.

E.g.
``` nodeattr -l node1
nodes
slave
cluster
all```
Then we will look for the files: all.yaml, cluster.yaml, slave.yaml, nodes.yaml

**Comment by ste78** [comment]
yep that sounds even better, as we'll be able to change the load order by just modifying the gender groups - lets go with that!
