### ISSUE TITLE
Multiple modes for pxe booting

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#164]
We need to support UEFI booting, to do that we need to extend the legacy PXE templating components. Primary differences in the process are:

- The template used to generate the actual boot file is grub based, which basically means it looks completely different to the current pxelinux.cfg template so potentially we need the option of 2 defaults (one for legacy and one for uefi)
- rather than being saved to /var/lib/tftpboot/pxelinux.cfg, files would need to be saved to /var/lib/tftpboot/efi/ 
- rather than being named <`gethostid 10.10.1.1`> the files need to be named <grub.cfg-`gethostid 10.10.0.1`> eg `/var/lib/tftpboot/pxelinux.cfg/0A0A0101` becomes `/var/lib/tftpboot/efi/grub.cfg-0A0A0101`
- the dhcp host entry needs to be slightly different on one of the fields, this could be done with the default dhcp template if we had either a config value or alces magic value to select the boot type of the node. 

IRL Nodes can only support legacy booting or UEFI booting at any one time so thinking about how this could be implemented, we could possibly have a config value for a node that said if it supports legacy or UEFI booting, defaulting to legacy booting at the domain level.

**Comment by bobwhitelock** [comment]
We implemented the ability to have different `build_method`s the other day, to allow a `basic` `build_method` along with the default (and previously only) `kickstart` `build_method`. From an initial look at this issue it seems the most straightforward way to add this would be to add a new build method to the existing 2, called for example `uefi`, which appropriately renders the `kickstart` along with a new `uefi` template. The `dhcp` template could then be changed appropriately to switch on the build method.

How does this sound @ste78?

**Comment by ste78** [comment]
yeah would probably do it, but it's still primarily a kickstart build method, so maybe call it `uefikickstart` or similar
