### ISSUE TITLE
Warnings and Errors in Rendering

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#182]
(enhancement logged on request by @WilliamMcCumstie)

In general, this approaches two aspects of the error/warning system of metalware, specifically:
1. Rendering failing due to an unused parameter not being set
2. Warning outputs not being clear on the source of the warning

**Rendering Failing**
Currently, if rendering a template for a node that isn't defined as part of a group (at the moment, this is seen with the `self` node) then there is no value set for `pri_network_defined`, this causes rendering to exit with an error even if the value isn't being used:
```
[root@controller ~]# echo '<%= alces.nodename %>' > /tmp/test
[root@controller ~]# metal render /tmp/test self
error: Unset template parameter: pri_network_defined. Use --trace to view backtrace
```

The above issue can be 'fixed' in `metalware-default` in a number of ways (requesting an answer for `pri_network_defined` at domain level, requesting it at self level, setting a default value in `configure.yaml`) 

**Warning Outputs**
To assist troubleshooting and improve general readability of warning outputs it would be beneficial to add information regarding where in the render the warning was generated. Currently, a render warning looks as follows:
```
warning: Unset template parameter: build_method
```
This could be improved with the filename, line number and maybe even the source ERB that was being rendered at the time of the warning being generated.

**Comment by WilliamMcCumstie** [comment]
Additional logging when an error occurs. It would be useful to know which file contain the error as typically metalware renders multiple files.

**Comment by WilliamMcCumstie** [comment]
As of `2017.2.0`, the config values are being rendered on demand and thus the build shouldn't fail if `pre_netword_defined` is unset (unless it is being used).

Some of the warnings have already been improved. See #210 for more details.

The final part is where the warnings are generated from. As this is not a crucial feature, it might be best to implement this as `2017.2.1`. That way it does not prevent the release of the new version.

@ColonelPanicks @ste78, thoughts?
