### ISSUE TITLE
`/etc/named.conf` should not be handled by metalware

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#183]
Much like how `/etc/dhcp/dhcpd.conf` is not handled by metalware, the named config file `/etc/named.conf` should not be templated and configured by metalware. The other named files (`/etc/named/metalware.conf`, forward and reverse zones in `/var/named`) should still be rendered as they are with no differences. It's just a matter of removing the `/etc/named` config.

(the configuration of `/etc/named.conf`, again much like `/etc/dhcp/dhcpd.conf`, should be handled by the user or the metalware-default repo)

**Comment by WilliamMcCumstie** [comment]
Ignore the link to #176. That was made incorrectly on the branch. The fix to this is contained in #184
