### ISSUE TITLE
Should `dhcpd.hosts` be generated by metalware GUI?

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#196]
From testing the GUI I've been able to hunt nodes and register them as part of a group but when trying to build I was getting no PXE response. It turns out that `dhcpd.hosts` was empty, requiring me to run `metal dhcp` before being able to build the node. 

Should `metal dhcp` be run after stopping hunter on the node? When clicking build for a node/group of nodes? Or maybe have its own button on the GUI?

**Comment by WilliamMcCumstie** [comment]
The `dhcp` command could probably be replaced with the `sync` command. See #203

**Comment by WilliamMcCumstie** [comment]
The `dhcp` command has been replaced by the `template` and `sync` command in #203
