### ISSUE TITLE
pdsh in metalware needs /opt/clusterware to exist 

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#2]
When running pdsh from metalware I get errors that /opt/clusterware/opt/pdsh/lib doesn't exist. It seems the binary has paths hardcoded? 
You can workaround for now by linking /opt/clusterware to /opt/metalware

**Comment by mjtko** [comment]
This happened when I rebuilt `pdsh` to have readline support as part of alces-software/clusterware#5 and reused the same tarball for metalware.  Oops. :)

I've now correctly rebuilt `pdsh` for metalware and uploaded to the S3 bucket for metalware.
