### ISSUE TITLE
Inconsistency in metalware's service management

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#203]
Currently, `metalware configure` regenerates `/etc/hosts` (or `/var/named/*`), `genders` and restarts services (like `named` if that's the chosen DNS solution). However, to restart dhcp and update `dhcpd.hosts` the command `metal dhcp` command needs to be run. 

There are a couple of options for sorting this:
1. Retire the `metal dhcp` command in favour of running the dhcp tasks at the end of configure
2. Separate all the system file modification and service management into a separate command (`metal sync`)

Thoughts?

**Comment by WilliamMcCumstie** [comment]
Instead of restarting `DHCP` or `named` behind the scenes.

Instead of doing it implicitly, so a `metal sync` command could be used to do it `explicitly`.

Do we want to call it `metal restart-service`?

**Comment by WilliamMcCumstie** [comment]
Also `metal build` should fail if metalware is not in `sync`

**Comment by WilliamMcCumstie** [comment]
This issue can be closed as basic service management has been implemented. Any additional changes can be requested as a separate issue.
