### ISSUE TITLE
Separate `configure.yaml` for Different Scopes

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#204]
Due to the wording of some questions and the need to switch up some defaults depending on domain/group/node it would be beneficial (much like the `answers` and `repo/config/` files) to separate the configuration files (possibly with similar merging to `repo/config` files).

Is this feasible? If so I'll modify the metalware-default to some sort of hierarchy like:
```
questions/configure.yaml
questions/group/configure.yaml
questions/node/configure.yaml
```

**Comment by ColonelPanicks** [comment]
(From chat with @WilliamMcCumstie )

### Alternative 1
The questions can be specified within the sections later on in `configure.yaml`, for example:
```
domain:
  - *cluster_name
```
Becomes:
```
domain:
  - &cluster_name
    identifier: cluster_name
    question: 'Cluster name'
```
Which allows for domain, groups and nodes to have separate questions and defaults. 

### Alternative 2
Keys within a question should be overridable later on, for example:
```
domain:
  - *cluster_name
```
Becomes:
```
domain:
  - *cluster_name: |
      question: "The name of the cluster"
```
However, while loading the file with `YAML.load_file('configure.yaml')` works, `metal configure domain` has the following error appear:
```
error: undefined method `to_sym' for {"identifier"=>"cluster_name", "question"=>"Cluster name"}:Hash
Did you mean?  to_s
               to_set. Use --trace to view backtrace
```
This is because of how the YAML is parsed, changing the parsed hash from:
```
{"identifier"=>"cluster_name", "question"=>"Cluster name"}
```
to:
```
{{"identifier"=>"cluster_name", "question"=>"Cluster name"}=>"", "question"=>"The name of the cluster"}
```
An alternative way of doing this inheritance is:
```
domain:
  - cluster_name:
     <<: *cluster_name
     question: 'The name of the cluster'
```
Which parses the yaml as:
```
{"cluster_name"=>{"identifier"=>"cluster_name", "question"=>"The name of the cluster"}}
```
Far closer to something that would work for us but this is still incompatible with `metal configure`:
```
error: An error occurred validating the questions. The following error(s) have been detected:
{:domain=>{0=>{:identifier=>["is missing"], :question=>["is missing"]}}}. Use --trace to view backtrace
```

**Comment by WilliamMcCumstie** [comment]
This can already be done by defining a separate questions under the corresponding `node`, `group`, `domain` arrays

Also `yaml` has special features that may allow this already.

**Comment by ColonelPanicks** [comment]
`metalware-repo-base` branch `feature/question-improvements` (https://github.com/alces-software/metalware-repo-base/tree/feature/question-improvements) looks to address different question wordings in content
