### ISSUE TITLE
Automatically Set IPMI Password in `/opt/metalware/etc/ipmi.conf`

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#206]
The IPMI password, while set during `metal configure`, requires manually updating in `/opt/metalware/etc/ipmi.conf` for `metal status` and `metal power` commands to work properly.

**Comment by WilliamMcCumstie** [comment]
Formally integrate `power` and `status` into ruby. Then render the `ipmi` password inside of `power` instead of reading the global `ipmi.conf`.

This needs to allow passwords at `domain`, `group`, or `node` level

**Comment by WilliamMcCumstie** [comment]
Look at removing `ipmi.conf`

**Comment by vlj91** [comment]
This was done with #265
