### ISSUE TITLE
Implement hooks for `metal build`

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#207]
Currently, metalware identifies when nodes have built due to the end of the build file curl'ing a php file (created as part of the controller setup in metalware-default [here](https://github.com/alces-software/metalware-default/blob/develop/files/setup/http.sh#L16)).

Ideally, we'd be able to display smaller progress steps for a build process (e.g. start, base install, custom scripts, complete). According to @ste78 there is similar functionality to this in clusterware.

**Comment by WilliamMcCumstie** [comment]
Look at using `flight trigger`

**Comment by WilliamMcCumstie** [comment]
Make an event directory within /vl/m/. Based on build complete files. Also allow a `YAML` payload to be read from the file.

**Comment by WilliamMcCumstie** [comment]
Am event can be triggered by writing to the node's sub directory within the `events` folder. Currently it dumps the file content to the screen. As the data isn't otherwise being used, it doesn't parse it as `YAML`. This can be added at a latter date when better integration with hooks is provided.
