### ISSUE TITLE
Plugins management

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#208]
At the moment, the knowledgebase contains guides and scripts for setting up additional, optional components to metalware. These could be further integrated (whilst staying separated from both metalware and the default repo) by implementing in a similar way to the `clusterware handler` setup. For example:
```
metal plugin enable ganglia,nagios
```
To download the scripts and make `domain.yaml` changes for Ganglia & Nagios client/server setup.

**Comment by bobwhitelock** [comment]
From meeting:

- change `plugin enable`/`plugin disable` to `activate`/`deactivate`, default to `activate`, drop these in `/var/lib/metalware/plugins`;

- put out pre-release for 2018.1.

**Comment by bobwhitelock** [comment]
With the release of [2018.1.0-rc1](https://github.com/alces-software/metalware/releases/tag/2018.1.0-rc1) the initial version of plugins has been completed and is ready for testing and use.
