### ISSUE TITLE
GUI default value is taken from group and not node

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#218]
Below is the output of a node being configured on the command line without any of its details being changed (note that Setup management network? is set to no, this is contrary to the group's configuration and was done intentionally):
```
[root@controller ~]# metal configure node node03
Root user encrypted password (1/15)  |$1$2FIea8vh$wCLQcFIVIJrh2Y5U8oXTW1|

Kickstart template to use (2/15)  |default|

PXELINUX template to use (3/15)  |default|

Setup primary network? (4/15) [yes/no]  |yes|

IP for nodes on the primary network (5/15)  |10.10.<%= alces.group_index %>.<%= alces.index %>|

Interface for the primary network (6/15)  |em1|

Setup management network? (7/15) [yes/no]  |no|

IP for nodes on the management network (8/15)  |10.11.<%= alces.group_index %>.<%= alces.index %>|

Interface for the management network (9/15)  |eth1|

Setup BMC management network? (10/15) [yes/no]  |no|

IP for nodes on the bmc network (11/15)  |10.11.<%= alces.group_index.to_i + 100%>.<%= alces.index %>|

Password for BMC device over LAN (12/15)  |Pa55Word|

Setup InfiniBand network? (13/15) [yes/no]  |yes|

IP for nodes on the InfiniBand network (14/15)  |10.12.<%= alces.group_index %>.<%= alces.index %>|

Interface for the InfiniBand network (15/15)  |ib0|
```

And below is what the same node looks like through the GUI (note how "Setup management network?" defaults to yes)

![screen shot 2017-09-26 at 18 10 19](https://user-images.githubusercontent.com/27725639/30873685-014153f2-a2e6-11e7-9ae2-8598c9c0e96c.png)

This seems to be nothing more than a display issue but could still cause confusion/frustration when configuring nodes!

**Comment by bobwhitelock** [comment]
The GUI is now being removed as obsolete, so this issue is no longer relevant. See https://github.com/alces-software/metalware/commit/7dea9a58 for details.
