### ISSUE TITLE
Update `/var/named/*` partially, like with `/etc/hosts`

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#225]
Named should replace parts of files with the hosts information, much like how metalware replaces between the `METALWARE START` and `METALWARE END` parts of `/etc/hosts` after adding more nodes.

This is slightly more difficult as the named configuration creates multiple files in `/var/named/` which contain zone configuration as well as host information.

Named would ideally be setup by (primary network used as an example):

1. Creating the zone file after `metal configure domain`
```
$TTL 300
@                       IN      SOA     . nobody.example.com. (
                                        1507302382   ; Serial
                                        600         ; Refresh
                                        1800         ; Retry
                                        604800       ; Expire
                                        300          ; TTL
                                        )

                        IN      NS      .
@       IN MX   10  pri.testcluster.cluster.local.

IN NS .

### METALWARE START ###
### METALWARE END ###
```

2. Rendering the hosts in-between the `METALWARE` tags

This may require changes in `metalware-default` as the zone information (from step 1) is included in the zone template file alongside the hosts information (see [`named/forward/default`](https://github.com/alces-software/metalware-default/blob/develop/named/forward/default))

**Comment by WilliamMcCumstie** [comment]
Use the managed section templating method
