### ISSUE TITLE
[2017.2.0-pre4] Local build doesn't execute properly

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#241]
When building the local node it hangs indefinitely and doesn't make any changes to the system. Suspicion is that the local build method is not calling the build script (`/var/lib/metalware/rendered/local/local`)  when `metal build local` is run.

The local run script - `/var/lib/metalware/rendered/local/local` - executes without issue from the command line.

**Comment by ColonelPanicks** [comment]
There were some issues with metalware-default that prevented the local script from running properly, these have been fixed - https://github.com/alces-software/metalware-default/commit/361c62a90688bd4c7040ca10b8aeeff84e2eb57a

**Comment by WilliamMcCumstie** [comment]
It looks like the start local build script isn't being ran and thus the build is hanging indefinitely. This bug will be fixed as part of the greater build refactor and will not be addressed directly. The issue will be remain open until such time it is fixed.

**Comment by ColonelPanicks** [comment]
@WilliamMcCumstie in more recent prebuilds (and the release candidate) this bug has been fixed, I couldn't locate a specific commit that fixed this but will close the bug anyway.
