### ISSUE TITLE
Orchestration Support [KVM]

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#242]
It would be useful to enable orchestration support with metalware so that it can be used to deploy virtual machines. 

Currently, the process for setting up remote management of the KVM system (and subsequently deploying VMs) is documented [here](http://cluster-platform-knowledgebase.readthedocs.io/en/latest/vm_deployment/vm_deployment.html) and uses these scripts:
- https://github.com/alces-software/knowledgebase/blob/master/epel/7/certificate_authority/certificate_authority.sh
- https://github.com/alces-software/knowledgebase/blob/master/epel/7/libvirt/vm.sh

To setup the certificate authority and deploy the VMs respectively.

Ideally, this would be further integrated with metalware such that metalware handles:
- Connecting the controller to a remote VM server (using TLS certificates)
- Deploy virtual machines (a BuildMethod which can deploy a virtual machine _and_ run the build command)
- Manage virtual machines through `metal power` by identifying which systems are VMs and instead querying libvirt instead of BMCs

**Comment by ColonelPanicks** [comment]
It looks like libvirt has official Ruby support - https://libvirt.org/ruby/

**Comment by vlj91** [comment]
Need to add Libvirt setup (certs etc) somewhere

**Comment by vlj91** [comment]
Add ability to open a console on a VM

**Comment by vlj91** [comment]
* Add certificate generation into installer, warn when can't connect to Libvirt host
* Console via system command

**Comment by bobwhitelock** [comment]
With the merging of @vlj91's recent PRs has this now been fully implemented?

**Comment by vlj91** [comment]
>Console support would be super but there's a couple of changes to the template in metalware-default required to make the console setup functional iirc

@ColonelPanicks, 2018

**Comment by bobwhitelock** [comment]
@vlj91 do you mean that part isn't done?
