### ISSUE TITLE
Metalware install final message displays incorrect information about certificates

### ISSUE THREAD

**Issue by vlj91** [alces-software/metalware#282]
#280 moved some of the certificate generation round, so libvirt host certificates are now generated post-install. The message after install reads:

```
If the Libvirt integration is required, please copy the following certificates
to the Libvirt host(s):

  from (local): /var/lib/metalware/certs/cacert.pem
   to (remote): /etc/pki/CA/cacert.pem (remote)

  from (local): /var/lib/metalware/certs/server-{key,cert}.pem
   to (remote): /etc/pki/libvirt/{servercert.pem,/private/serverkey.pem}
```

The last section (`server-{key,cert}`) etc should be removed - as that message appears later when configuring nodes.

**Comment by bobwhitelock** [comment]
This seems a sensible and easy change, so go for it when you get a chance @vlj91 :slightly_smiling_face:
