### ISSUE TITLE
[VM Orchestration] Destroy command requires VMs to be running

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#283]
The `destroy` command, as I understand, is designed to delete images and undefine the VM configurations on the master. In the event that the VM config is incorrect it is impossible to start the VMs and the VMs have to be manually removed due to the `destroy` restriction on VMs being running.

**Comment by vlj91** [comment]
This is quite a simple fix - I think I had a check in before to only power off the domains if they are already running. Not sure where that check went, but it can easily be added back again. A domain needs to be off in order to undefine it.
