### ISSUE TITLE
Simpler Command for Showing Domain/Group Summary

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#284]
Currently, the `metal view` command is useful for checking a ton of configuration parameters at once but it would be helpful to have commands that are simpler. For example, a command to dump a few configuration details to give an idea of the cluster configuration in the event of revisiting a cluster for the first time in a few months. Would be great if it can do the following:

- Display cluster general configuration
  - Cluster Name
  - Domain
  - DNS Config

- Display table of group configuration (where group name is a primary group configured by metalware)

| Group Name | Additional Groups | Nodes |
|-|-|-|
| nodes | physical,compute,cluster,all | node[001-100] |
| infra | virtual,service,cluster,all | infra[01-03] |

**Comment by bobwhitelock** [comment]
Call 'metal overview'.
