### ISSUE TITLE
Content Repositories

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#29]
Metalware now has a large amount of configuration data / scripts / templates that can be described better as content.
This enhancement is to add functionality to refactor where this data is located into separate standalone component dirs. 

I've done an example of a 'repo' here: https://github.com/alces-software/metalware-profile-hpc

Basically this is to add a 'metalware repo' action that can 'import' a repo from a git URL into /var/lib/metalware/repos/`reponame`/. Extended functionality could also provide 'list' and 'update' functionality to this.

The idea would then be that when running commands that use templates / configs you'd use '--repo myrepo' which would use configs / templates from that repo, rather than the default one in metalware/etc/

**Comment by BobWhitelock** [comment]
This has been done.
