### ISSUE TITLE
IPMI Command Errors

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#296]
When checking the power status with `metal power` it throws out an error that seems to indicate the the node object is being passed to the command instead of `node.name`:
```
[root@controller repo]# metal power node097 status
error: 'ipmitool -H #<Metalware::Namespaces::Node:0x00000002a9ee88, name: node097>.bmc -U 2 -P liugJac1 chassis power status' produced error 'ipmitool: option requires an argument -- 'H'
```

This effects all arguments to the `metal power` command and, I assume, is why `metal status` is also error-ing on the power check.

**Comment by bobwhitelock** [comment]
@vlj91 I believe you changed how `power` works last - can you investigate when you have a moment?

**Comment by bobwhitelock** [comment]
I believe this was fixed in https://github.com/alces-software/metalware/pull/297, please reopen if not.
