### ISSUE TITLE
metal console no longer working

### ISSUE THREAD

**Issue by wdm78** [alces-software/metalware#326]
metal console seems to be broken for ipmi nodes, metal power works as expected but metal console seems to be talking to the wrong host (in this example the ipmi hostname passed to -H should be node001.bmc, not node001)

```
[root@controller [cluster] ~]# metal console node001
error: 'ipmitool -H node001 -I lanplus -U admin -P ******* -e '&' sol info' produced error 'Error: Unable to establish IPMI v2 / RMCP+ session'. Use --trace to view backtrace
```

**Comment by bobwhitelock** [comment]
I'm investigating

**Comment by WilliamMcCumstie** [comment]
This is probably related to my fix last week

https://github.com/alces-software/metalware/issues/323

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie I thought it might be but looking through `git log` I don't think it is - AFAICS we've never used `$node_name.bmc` for `console`, and I left a comment wondering about this when I did some refactoring of the `ipmi` commands: https://github.com/alces-software/metalware/blob/d50f2e6b08d2793b3ce18ca2b6a26534350a6338/src/commands/console.rb#L44-L46.

**Comment by WilliamMcCumstie** [comment]
Well if it is meant to be `#{node.name}.bmc`, then we can remove the `hosts` input
