### ISSUE TITLE
New template file structure

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#35]
Once the repo system is working it would be good to standardize how we store the default repository. This will require:
1. Moving the default repo out of `metalware` and into it's own repository. Therefore it can be updated independently to `metalware`
2. As everything in the template repos are templates, we can remove the template directory. Will need to move it's contents (`boot`, `kickstart`, ...) up one directory.
3. Move the install location of the default repo into `/var/lib/metalware/repos/default`

**Comment by BobWhitelock** [comment]
This has been done.
