### ISSUE TITLE
Asset database

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#351]
Add cli functionality to collect asset information about various assets and then link those assets to the logical node / node groups that metalware currently manages.

Well need to go more in depth with requirements but for overview i’m thinking

metal add rack
metal add chassis
metal add server
metal add vm
metal add switch
metal add disk

some asset info. to think about:

type = rack/chassis/server/vm/switch/disk/cloud/pdu
name/brand
serial
configuration profile / description
*management info - ip/netmask/gatway username/password
*parent
*expansions

example expansions are:
-psu/network/disk

some asset types will have specific info, eg:

rack/chassis - slots & slot orientation 
server/vm/disk/cloud - disk configuration profile 
server/vm/cloud - link to a gender group member via ‘hostname’ 

we then need to add an metal export command that supplies a file capable of being imported into flightcenter that’ll give it something similar to the data it currently holds about all of a clusters components

**Comment by bobwhitelock** [comment]
I believe this has now been entirely done or is otherwise obsolete, as we now handle importing assets into Flight Center via Benchware; therefore closing.
