### ISSUE TITLE
Node status tool

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#38]
Add a node status tool to metalware to report on if metal nodes are available and if they are contactable on the network. Eg:

```
$> metal status -g mynodes
---------------------------------
| node01 | Power ON  | Ping OK |
| node01 | Power OFF | No Ping |
--------------------------------
```

power ON/OFF would come from using the ipmi power status metal command, and Ping status would come from executing a ping -c 1 against the node. 

We should make the command deal with bad nodes nicely as well, so if there is no ipmi power response then we should timeout checking in a reasonable amount of time, and if the ping doesnt respond then again the timeout should not take long ( perhaps we could run the commands in parallel rather than serial to gather the information quicker?)

**Comment by WilliamMcCumstie** [comment]
Limit monitor to 50 forks at a time

**Comment by BobWhitelock** [comment]
This exists as described in [1.2.0](https://github.com/alces-software/metalware/releases/tag/1.2.0) I believe.
