### ISSUE TITLE
Combined and configurable template feature

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#42]
Metalware now has multiple features that all rely on the templater to operate. However as they are implemented as separate features, their is significant overhead when adding a new type of template. Also each feature operates in slightly different manor and is reducing usability.

***Proposed Change:***  
*Combine Template Features*
Combine the templating features `kickstart`, `scripts` and `hosts` so that they operate through a unified template feature (e.g. `metal template <action>`). Also remove the template aspects of `boot` into the new feature.

*Configurable*
Include a config file with all the `actions`, save mode (`display`, `save` or `append`) and save locations. 

***Additional Requirements***
1. Standardize how the save files are represented and integrate with erb templater
1. Include the save filename into the hash so available to the templates. E.g.
    1. `/var/lib/metalware/rendered/scripts/<%= nodename %>/<%= scripts_filename %>`
1. Two modes of operation:
    1. From command line
    1. From another ruby file via a require
1. Export and import save file names so that they can be included into another template action. Note save file key may need to be `<action>_filename`

***Issues***
1. When multiple templates are installed, can the new config file be overridden? (Probably no to start)
1. Some actions save while others append by default
1. Clean up variable passing between CLI and ruby file
1. Some features may have two commands. Example `metal template boot` would only render `boot` templates while `metal boot` would render the templates and tear them back down
1. Modify `--template-options`, a lot of the info should go into the wiki. Only the constants really need to be displayed

**Comment by BobWhitelock** [comment]
This has largely been made obsolete by the plans for Metalware 2.0.
