### ISSUE TITLE
Straighten Out Hostname/Nodename Usage in Identifying Node IP

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#432]
Recently @bobwhitelock ran into the following error:
```
[root@controller [asset-example] metalware]# metal view nodes.local.to_h
error: 'gethostip -x local' produced error 'local: Unknown host'.
```

This is an expected error due to metalware using `node.name` (`local`) for the host IP lookup. In the case of the local node, it never shares its hostname with its nodename, usually the local node network hostname is `controller`.

As I see it there are a couple of options for resolving this:
- Use the primary network hostname (`node.config.networks.pri.short_hostname`) for the node when doing `gethostip`
- Locate IP address for a node via its config instead of querying DNS (`node.config.networks.pri.ip`)
- Tweak this error to be non-critical so that the config viewing can proceed

What are your thoughts on this issue?

**Comment by bobwhitelock** [comment]
Don't know enough about how we currently use this part of Metalware/how we want this to work, but I agree we should do something to fix this; the current behaviour is annoying and requires hacking `/etc/hosts` for `metal view` to work for all nodes.

**Comment by bobwhitelock** [comment]
This issue was moved to alces-software/underware#3
