### ISSUE TITLE
Basic build_method not rendering appropriate build files

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#439]
Original issue for adding build_method - https://github.com/alces-software/metalware/issues/145

When using basic build_method on a node I'd expect it to render `basic/default` from the metalware repo however what seems to happen is that it just runs a pxe_kickstart build method (as I can see it putting in place `rendered/kickstart/nodename` and `/var/lib/tftpboot/pxelinux.cfg/nodename`). 

Am I misunderstanding the basic build method implementation? The idea was that it could create a file we could curl to begin the installation.

**Comment by bobwhitelock** [comment]
@ColonelPanicks do you have a machine I can use to try this out + minimal steps to reproduce?
