### ISSUE TITLE
Allow plugin enable question to be passed to --answers

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#444]
It would be beneficial to be able to enable/disable plugins via the `metal configure --answers` method, currently what happens with these answers is:
```
[root@gateway ~]# metal configure domain --answers '{ "metalware_internal--plugin_enabled--firstrun": "true" }'
error: Failed to validate answers:
A type mismatch has been detected in the following question(s):
{:question=>:"metalware_internal--plugin_enabled--firstrun", :answer=>"true", :type=>"boolean"}
```

Currently the workaround is to echo these values to the answers file which works without issue.

**Comment by ColonelPanicks** [comment]
Ahhh darn, that's the ticket. My bad. This isn't an issue then!

**Comment by bobwhitelock** [comment]
No worries, `"true" != true` :slightly_smiling_face:.
