### ISSUE TITLE
Unified Error Class

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#54]
I have noticed their is a few errors in `repo update` and possible elsewhere that are based on `StandardError`. We should look to move these to the metalware `Exception` class

**Comment by bobwhitelock** [comment]
Closing; this is pretty minor and covered by https://trello.com/c/UAFw8ohK/111-have-all-errors-be-instances-of-metalwareerror and https://trello.com/c/HLPwJePq/88-change-rugged-errors-to-metalware-errors-in-repo-use.
